name: Tests and linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  protostar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash

      - name: Install protostar dependencies
        run: /home/runner/.protostar/dist/protostar/protostar install

      - name: Compile smart contracts
        run: /home/runner/.protostar/dist/protostar/protostar build-cairo0

      - name: Run protostar tests
        run: /home/runner/.protostar/dist/protostar/protostar test-cairo0
